version: '3.9'

services:
  mongodb_auth:
    hostname: ${AUTH_MONGO_CONTAINER_NAME}
    container_name: ${AUTH_MONGO_CONTAINER_NAME}
    image: 'visualboost/mongo:6.0'
    command: [ "--port", "${MONGO_PORT_AUTH}", "--bind_ip_all", "--auth", "--keyFile", "repl_auth.key", "--replSet", "repl_auth" ]
    restart: 'on-failure'
    expose:
      - ${MONGO_PORT_AUTH}
    ports:
      - ${MONGO_PORT_AUTH}:${MONGO_PORT_AUTH}
    networks:
      - visual_boost_auth_network
    volumes:
      - ./home/mongodb:/home/mongodb #Necessary for mongosh
      - ${MONGO_DATA_DIR_AUTH}:/data/db #data directory
      - ./init/init_replicaset.sh:/docker-entrypoint-initdb.d/init_replicaset.sh:ro #init replicaset script
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u $${MONGO_ADMIN} -p $${MONGO_ADMIN_PW} --quiet | grep 1
      interval: 30s
      start_period: 60s
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ADMIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ADMIN_PW}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
      - MONGO_USER=${MONGO_USER}
      - MONGO_USER_PW=${MONGO_USER_PW}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_PORT=${MONGO_PORT_AUTH} # Necessary to initialize replicaset
      - MONGO_URL=${AUTH_MONGO_CONTAINER_NAME} # Necessary to initialize replicaset

networks:
  visual_boost_auth_network:
    name: ${NETWORK_AUTH}
