version: '3.9'

# Include database configs
include:
    - ./../container/auth/database/db.yml
    - ./../container/main/database/db.yml
    - ./../container/build/database/db.yml

services:
    auth:
        extends:
            file: ./../container/auth/auth.yml
            service: auth_app
        networks:
            - visualboost
        depends_on:
            - mongodb_auth
        volumes:
            - ${LOG_DIR_AUTH}:/logs #Directory for log files
        labels:
            - "traefik.enable=true" #Detect this service
            - "traefik.http.routers.auth.entrypoints=visualboost" #Listen on Port ${PROXY_PORT}
            - "traefik.http.routers.auth.rule=Host(`${DOMAIN}`) && PathPrefix(`${PROXY_PATH_AUTH}`)" #Forward to this service when the domain with the path ${PROXY_PATH_AUTH} is called
            - "traefik.http.services.auth.loadbalancer.server.port=${HTTP_PORT_AUTH}" # Forward request to port ${HTTP_PORT_AUTH}

            #Remove ${PROXY_PATH_AUTH} before accessing this service. The original service does only listen on localhost:${HTTP_PORT_AUTH}.
            - "traefik.http.middlewares.strip-auth.stripprefix.prefixes=${PROXY_PATH_AUTH}"
            - "traefik.http.routers.auth.middlewares=strip-auth@docker"

#            - "traefik.http.routers.auth.tls.certresolver=sslresolver" #Necessary when running on a remote server with a letsencrypt certificate
        environment:
            - SSL_ENABLED=true #if SSL_ENABLED=false the service uses http:// instead of https://
            - PROXY_PORT=${PROXY_PORT} #Necessary for email authentication
            - PROXY_PATH=${PROXY_PATH_AUTH} #Necessary for email authentication
            - DEBUG=false #Logs all requests

    main:
        extends:
            file: ./../container/main/main.yml
            service: main_app
        volumes:
            - ${LOG_DIR_MAIN}:/logs #Directory for log files
        labels:
            - "traefik.enable=true" #Detect this service
            - "traefik.http.routers.main.entrypoints=visualboost" #Listen on Port ${PROXY_PORT}
            - "traefik.http.routers.main.rule=Host(`${DOMAIN}`) && PathPrefix(`${PROXY_PATH_MAIN}`)" #Forward to this service when the domain with the path ${PROXY_PATH_MAIN} is called
            - "traefik.http.services.main.loadbalancer.server.port=${HTTP_PORT_MAIN}" # Forward request to port ${HTTP_PORT_MAIN}

            #Remove ${PROXY_PATH_MAIN} before accessing this service. The original service does only listen on localhost:${HTTP_PORT_MAIN}.
            - "traefik.http.middlewares.strip-main.stripprefix.prefixes=${PROXY_PATH_MAIN}"
            - "traefik.http.routers.main.middlewares=strip-main@docker"

#            - "traefik.http.routers.main.tls.certresolver=sslresolver" #Necessary when running on a remote server with a letsencrypt certificate
        networks:
            - visualboost
        depends_on:
            - mongodb_main
            - auth

    build:
        extends:
            file: ./../container/build/build.yml
            service: build_app
        volumes:
            - ${LOG_DIR_BUILD}:/logs #Directory for log files
        labels:
            - "traefik.enable=true" #Detect this service
            - "traefik.http.routers.build.entrypoints=visualboost" #Listen on Port ${PROXY_PORT}
            - "traefik.http.routers.build.rule=Host(`${DOMAIN}`) && PathPrefix(`${PROXY_PATH_BUILD}`)" #Forward to this service when the domain with the path ${PROXY_PATH_BUILD} is called
            - "traefik.http.services.build.loadbalancer.server.port=${HTTP_PORT_BUILD}" # Forward request to port ${HTTP_PORT_BUILD}

            #Remove ${PROXY_PATH_BUILD} before accessing this service. The original service does only listen on localhost:${HTTP_PORT_BUILD}.
            - "traefik.http.middlewares.strip-build.stripprefix.prefixes=${PROXY_PATH_BUILD}"
            - "traefik.http.routers.build.middlewares=strip-build@docker"

#            - "traefik.http.routers.build.tls.certresolver=sslresolver" #Necessary when running on a remote server with a letsencrypt certificate
        networks:
            - visualboost
        depends_on:
            - mongodb_build
            - main

    react:
        extends:
            file: ./../container/react/react.yml
            service: react_app
        volumes:
            - ./nginx/templates:/etc/nginx/templates/
            - ${LOG_DIR_NGINX}:/logs/nginx/ #Directory for log files
        labels:
            - "traefik.enable=true" #Detect this service
            - "traefik.http.routers.react.entrypoints=visualboost" #Listen on Port ${PROXY_PORT}
            - "traefik.http.routers.react.rule=Host(`${DOMAIN}`)"  # Forward to react container when calling ${DOMAIN}
            - "traefik.http.services.react.loadbalancer.server.port=${HTTP_PORT_REACT}" # Forward request to port ${HTTP_PORT_REACT}

#            - "traefik.http.routers.react.tls.certresolver=sslresolver" #Necessary when running on a remote server with a letsencrypt certificate
        networks:
            - visualboost
        environment:
            - SSL_ENABLED=true #if SSL_ENABLED=false the service uses http:// instead of https://
        depends_on:
            - build

    reverse_proxy:
            container_name: "visualboost_reverse_proxy"
            image: traefik:v2.10
            command:
                - "--providers.docker" #run traefik with docker
                - "--providers.docker.exposedByDefault=false" #avoid that traefik auto detect the docker services
                - "--providers.docker.network=${NETWORK}" #set docker network
                - "--entrypoints.visualboost.address=:${PROXY_PORT}" #traefik listen on port ${PROXY_PORT}

#                - "--certificatesresolvers.sslresolver.acme.tlschallenge=true" #Necessary when running on a remote server with a letsencrypt certificate
#                - "--certificatesresolvers.sslresolver.acme.email=${LETS_ENCRYPT_MAIL}" #Necessary when running on a remote server with a letsencrypt certificate
#                - "--certificatesresolvers.sslresolver.acme.storage=/letsencrypt/acme.json" #Necessary when running on a remote server with a letsencrypt certificate

                #- "--log.level=DEBUG" #Enable Logging
            ports:
                - "${PROXY_PORT}:${PROXY_PORT}"
            volumes:
                - /var/run/docker.sock:/var/run/docker.sock:ro
                # - ./letsencrypt:/letsencrypt #Necessary when running on a remote server with a letsencrypt certificate
            networks:
                - visualboost
            depends_on:
                - react

networks:
   visualboost:
       name: ${NETWORK}
